version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 60
  ApplicationStop:
    - location: scripts/stop_application.sh
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: